title: Maze Project
author:
  name: Najib Muhammad
  email: najibm38@gmail.com

Description: >
  An maze game using SDL2 and raycast, enjoy!

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - features.md
  - about.md

minima:
  skin: classic
